sudo: required
language: python
services:
  - docker

#before_install:
#  - sudo pip install docker-compose

script:
  - docker-compose run app python -c"import timeside.core; timeside.core.list_processors()"